print("Enter your first number")
n1 = input()
print("Enter your second number")
n2 = input()
print("Solution:")
print("Sum of numbers:")
print(float(n1) + float(n2))
print("Difference of numbers:")
print(float(n1) - float(n2))
print("Product of numbers:")
print(float(n1) * float(n2))
print("Division of numbers:")
print(float(n1) / float(n2))
print("Thank you for using my calculator.Hope you like it...")